######################################################################
# Automatically generated by qmake (2.00a) dom 13. nov 14:44:29 2005
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += camera.h iframe.h pxc.h
SOURCES += camera.cpp main.cpp
RESOURCES += camera.qrc
win32:LIBS += ./ilib_32.lib C:\Dev-Cpp\lib\libgdi32.a
